<script setup lang="ts">
import { ZtConfigProvider, ZtButton, ZtInput } from '@ztechjs/zt-ui'
import DemoBlock from '../../components/DemoBlock.vue'
import Playground from './Playground.vue'
import codePlayground from './Playground.vue?raw'
import { sfc } from '../../utils/exampleCode'
const codeBasic=sfc("import { ZtConfigProvider, ZtButton, ZtInput } from '@ztechjs/zt-ui'",'<ZtConfigProvider size="large" theme="light" :border-radius="6">\n  <ZtInput placeholder="继承全局 large" />\n  <ZtButton status="primary">保存</ZtButton>\n  <ZtButton size="small">单独设置 small</ZtButton>\n</ZtConfigProvider>')
const codeNested=sfc("import { ZtConfigProvider, ZtButton, ZtInput } from '@ztechjs/zt-ui'",'<ZtConfigProvider size="large" theme="dark" :border-radius="12" style="padding: 20px">\n  <ZtButton>继承 dark / large</ZtButton>\n  <ZtConfigProvider size="mini" theme="light" :border-radius="0" style="padding: 20px; margin-top: 16px">\n    <ZtInput placeholder="局部 light / mini / 直角" />\n    <ZtButton>局部覆盖</ZtButton>\n  </ZtConfigProvider>\n</ZtConfigProvider>')
</script>
<template><article class="doc-section"><h1>ConfigProvider 全局配置</h1><p>为内部组件统一设置尺寸、明暗主题和圆角基准。支持动态切换及嵌套覆盖，不修改页面根节点，也不会影响作用域外的组件。</p><h2>基础用法</h2><DemoBlock :code="codeBasic" desc="在应用根部包裹一次即可；组件上显式设置的 size 优先，包括 default。"><ZtConfigProvider size="large" theme="light" :border-radius="6" style="display:flex;gap:12px;flex-wrap:wrap"><ZtInput placeholder="继承全局 large" style="width:220px" /><ZtButton status="primary">保存</ZtButton><ZtButton size="small">单独设置 small</ZtButton></ZtConfigProvider></DemoBlock><h2>动态配置体验</h2><DemoBlock :code="codePlayground" desc="切换尺寸、主题和圆角后，尝试打开选择器、日期范围、弹窗和抽屉；这些浮层也会继承配置。"><Playground /></DemoBlock><h2>嵌套与局部覆盖</h2><DemoBlock :code="codeNested" desc="内层 Provider 未设置的属性继续继承父级。显式 light 可在 dark 范围内恢复亮色，0 可创建直角控件。"><ZtConfigProvider size="large" theme="dark" :border-radius="12" style="padding:20px"><ZtButton>继承 dark / large</ZtButton><ZtConfigProvider size="mini" theme="light" :border-radius="0" style="padding:20px;margin-top:16px"><ZtInput placeholder="局部 light / mini / 直角" /><ZtButton style="margin-top:12px">局部覆盖</ZtButton></ZtConfigProvider></ZtConfigProvider></DemoBlock><h2>配置优先级</h2><p>组件显式 size 优先，其次为 FormItem / Form 或 RadioGroup / CheckboxGroup 的尺寸，最后使用最近一层 ConfigProvider。未提供任何配置时保持原有 default 尺寸、light 主题和 11px 圆角基准。</p><p>borderRadius 的单位为像素，各组件按原有圆角比例缩放。圆形按钮、单选圆点、开关滑块和胶囊标签保持其形状。负数或非有限数字忽略并继承父级。</p><p>Drawer 的 size 仍表示面板宽高，不受全局五档 size 改写。VTableGrid 的原生 theme 若通过 tableOptions 显式设置，会优先于全局主题。业务自定义插槽中的颜色需自行适配。</p><h2>API</h2><h3>Props</h3><table class="doc-table"><thead><tr><th>属性</th><th>类型</th><th>默认值</th><th>说明</th></tr></thead><tbody><tr><td>size</td><td>mini | small | default | medium | large</td><td>继承父级 / default</td><td>子组件的默认尺寸，可被组件或表单显式配置覆盖。</td></tr><tr><td>theme</td><td>light | dark</td><td>继承父级 / light</td><td>子组件的配色与原生控件 color-scheme，包含 Teleport 浮层。</td></tr><tr><td>borderRadius</td><td>number</td><td>继承父级 / 11</td><td>圆角基准，单位 px；0 为直角，圆形与胶囊控件保持形状。</td></tr></tbody></table><h3>Slots</h3><p>default：需要应用配置的组件。Provider 渲染一个 div 容器，可通过 class、style 设置布局和背景。</p></article></template>
