import { mount, flushPromises } from '@vue/test-utils'
import { describe, expect, it, vi } from 'vitest'
import { ZtMenu } from '../src'
const items=[{key:'home',label:'首页'},{key:'work',label:'工作空间',children:[{key:'group',label:'业务',type:'group' as const,children:[{key:'orders',label:'订单'},{key:'reports',label:'报表',children:[{key:'daily',label:'日报'}]}]}]},{key:'disabled',label:'禁用',disabled:true}]
const row=(key:string)=>document.querySelector<HTMLElement>(`[data-horizontal-key="${key}"]`)!
describe('horizontal menu',()=>{
 it('opens nested click menus and selects a leaf without changing collapsed state',async()=>{
  const w=mount(ZtMenu,{attachTo:document.body,props:{items,mode:'horizontal',menuTrigger:'click',collapsed:true,collapsible:true,resizable:true}})
  expect(w.find('[role=menubar]').exists()).toBe(true)
  expect(w.find('.zt-menu__collapse').exists()).toBe(false)
  row('work').click();await flushPromises()
  expect(document.querySelector('[aria-label="工作空间"][role=menu]')).not.toBeNull()
  row('reports').click();await flushPromises()
  expect(document.querySelectorAll('.zt-menu__horizontal-popup')).toHaveLength(2)
  row('daily').click();await flushPromises()
  expect(w.emitted('select')![0]![0]).toBe('daily')
  expect(row('work').classList.contains('is-selected')).toBe(true)
  expect(document.querySelectorAll('.zt-menu__horizontal-popup')).toHaveLength(0)
  expect(w.emitted('update:collapsed')).toBeUndefined()
  w.unmount()
 })
 it('supports hover dismissal, disabled items and outside click',async()=>{
  vi.useFakeTimers()
  const w=mount(ZtMenu,{attachTo:document.body,props:{items,mode:'horizontal'}})
  await w.get('.zt-menu__horizontal > li:nth-child(2)').trigger('pointerenter')
  await flushPromises()
  expect(document.querySelector('.zt-menu__horizontal-popup')).not.toBeNull()
  row('work').click();await flushPromises()
  expect(document.querySelector('.zt-menu__horizontal-popup')).not.toBeNull()
  await w.get('.zt-menu__horizontal > li:nth-child(2)').trigger('pointerleave')
  await vi.advanceTimersByTimeAsync(200)
  expect(document.querySelector('.zt-menu__horizontal-popup')).toBeNull()
  row('disabled').click();await flushPromises()
  expect(w.emitted('select')).toBeUndefined()
  row('work').click();await flushPromises()
  document.body.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));await flushPromises()
  expect(document.querySelector('.zt-menu__horizontal-popup')).toBeNull()
  w.unmount();vi.useRealTimers()
 })
 it('navigates the menubar and nested menus with arrow keys and Escape',async()=>{
  const w=mount(ZtMenu,{attachTo:document.body,props:{items,mode:'horizontal'}})
  await w.get('[data-horizontal-key=home]').trigger('keydown',{key:'ArrowRight'})
  expect(document.activeElement).toBe(row('work'))
  await w.get('[data-horizontal-key=work]').trigger('keydown',{key:'ArrowDown'})
  await flushPromises()
  expect(document.activeElement).toBe(row('orders'))
  row('orders').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));await flushPromises()
  expect(document.activeElement).toBe(row('reports'))
  row('reports').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await flushPromises()
  expect(document.activeElement).toBe(row('daily'))
  row('daily').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await flushPromises()
  expect(document.activeElement).toBe(row('reports'))
  row('reports').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await flushPromises()
  expect(document.activeElement).toBe(row('work'))
  w.unmount()
 })
})
