import { mount } from '@vue/test-utils'
import { h } from 'vue'
import { describe, expect, it, vi } from 'vitest'
import { ZtMenu, ZtConfigProvider } from '../src'
import type { ZtMenuItem } from '../src'
const items:ZtMenuItem[]=[{key:'a',label:'概览',href:'/overview'},{key:'b',label:'禁用',disabled:true},{key:'tree',label:'业务',children:[{key:'orders',label:'订单'},{key:'goods',label:'商品',children:[{key:'stock',label:'库存'}]}]},{key:'settings',label:'设置',children:[{key:'users',label:'用户'}]}]
const row=(w:ReturnType<typeof mount>,key:string)=>w.get(`[data-menu-key="${key}"]`)
describe('Menu',()=>{
 it('selects a leaf and preserves a link for router integration',async()=>{
  const w=mount(ZtMenu,{props:{items}})
  await row(w,'a').trigger('click')
  expect(w.emitted('update:modelValue')).toEqual([['a']])
  expect(row(w,'a').attributes('href')).toBe('/overview')
  expect(row(w,'a').attributes('aria-current')).toBe('page')
  expect(w.emitted('select')![0]![1]).toMatchObject({key:'a'})
 })
 it('allows modifier-click links without changing the current selection',async()=>{
  const w=mount(ZtMenu,{props:{items}})
  await row(w,'a').trigger('click',{ctrlKey:true})
  expect(w.emitted('select')).toBeUndefined()
 })
 it('toggles branches without selecting them and supports accordion',async()=>{
  const w=mount(ZtMenu,{props:{items,accordion:true}})
  await row(w,'tree').trigger('click')
  expect(row(w,'tree').attributes('aria-expanded')).toBe('true')
  expect(w.emitted('select')).toBeUndefined()
  await row(w,'settings').trigger('click')
  expect(row(w,'tree').attributes('aria-expanded')).toBe('false')
  expect(w.emitted('expand-change')!.at(-1)).toEqual([['settings']])
 })
 it('keeps controlled expansion until parent accepts the update',async()=>{
  const w=mount(ZtMenu,{props:{items,expandedKeys:[]}})
  await row(w,'tree').trigger('click')
  expect(row(w,'tree').attributes('aria-expanded')).toBe('false')
  await w.setProps({expandedKeys:['tree']})
  expect(row(w,'orders').isVisible()).toBe(true)
 })
 it('blocks disabled items and descendants',async()=>{
  const w=mount(ZtMenu,{props:{items:[{key:'parent',label:'父项',disabled:true,children:[{key:'child',label:'子项'}]}],defaultExpandedKeys:['parent']}})
  await row(w,'child').trigger('click')
  expect(row(w,'child').attributes('aria-disabled')).toBe('true')
  expect(w.emitted('select')).toBeUndefined()
 })
 it('moves focus past disabled rows, into a branch and back to its parent',async()=>{
  const w=mount(ZtMenu,{attachTo:document.body,props:{items}})
  await row(w,'a').trigger('keydown',{key:'ArrowDown'})
  expect(document.activeElement).toBe(row(w,'tree').element)
  await row(w,'tree').trigger('keydown',{key:'ArrowRight'})
  await new Promise(resolve=>setTimeout(resolve,0))
  expect(document.activeElement).toBe(row(w,'orders').element)
  await row(w,'orders').trigger('keydown',{key:'Escape'})
  expect(document.activeElement).toBe(row(w,'tree').element)
  expect(row(w,'tree').attributes('aria-expanded')).toBe('false')
  w.unmount()
 })
 it('maintains one tab stop when options change',async()=>{
  const w=mount(ZtMenu,{props:{items,modelValue:'a'}})
  expect(w.findAll('[tabindex="0"]')).toHaveLength(1)
  await w.setProps({items:[{key:'new',label:'新项'}]})
  expect(row(w,'new').attributes('tabindex')).toBe('0')
 })
 it('renders groups and inherits configuration',()=>{
  const w=mount(ZtConfigProvider,{props:{size:'large',theme:'dark'},slots:{default:()=>h(ZtMenu,{items:[{key:'group',label:'分组',type:'group',children:items}]})}})
  expect(w.get('.zt-menu').classes()).toContain('zt-menu--large')
  expect(w.get('[role=group]').attributes('aria-labelledby')).toBeTruthy()
  expect(w.get('.zt-menu__heading').text()).toBe('分组')
 })
})

describe('Menu layouts',()=>{
 const modules:ZtMenuItem[]=[{key:'sales',label:'销售',children:[{key:'orders',label:'订单'},{key:'refunds',label:'售后'}]},{key:'team',label:'组织',children:[{key:'members',label:'成员'}]},{key:'blocked',label:'不可用',disabled:true,children:[{key:'secret',label:'隐藏'}]}]
 it.each(['default','primary','success','warning','danger','info'] as const)('supports the %s theme',status=>{
  const w=mount(ZtMenu,{props:{items,status}})
  expect(w.classes()).toContain(`zt-menu--status-${status}`)
 })
 it('keeps the entire tree collapsed while navigating a flyout',async()=>{
  const w=mount(ZtMenu,{attachTo:document.body,props:{items,collapsed:true,collapsible:true,width:280,defaultExpandedKeys:['tree']}})
  expect(w.attributes('style')).toContain('56px')
  expect(row(w,'orders').isVisible()).toBe(false)
  await row(w,'tree').trigger('click')
  expect(w.emitted('update:collapsed')).toBeUndefined()
  const panel=document.querySelector('.zt-menu__flyout')!
  expect(panel.textContent).toContain('订单')
  ;(panel.querySelector('[data-menu-key=orders]') as HTMLElement).click()
  await w.vm.$nextTick()
  expect(document.querySelector('.zt-menu__flyout')).toBeNull()
  expect(w.emitted('update:modelValue')).toEqual([['orders']])
  expect(w.classes()).toContain('is-collapsed')
  w.unmount()
 })
 it('updates width dynamically and clamps pointer resizing',async()=>{
  const w=mount(ZtMenu,{props:{items,width:240,resizable:true,minWidth:180,maxWidth:320}})
  await w.setProps({width:280})
  expect(w.attributes('style')).toContain('280px')
  vi.spyOn(w.element,'getBoundingClientRect').mockReturnValue({width:280} as DOMRect)
  const handle=w.get('[role=separator]')
  await handle.trigger('pointerdown',{button:0,pointerId:1,clientX:280})
  await handle.trigger('pointermove',{pointerId:1,clientX:900})
  expect(w.emitted('update:width')!.at(-1)).toEqual([320])
  await handle.trigger('pointerup',{pointerId:1})
  await handle.trigger('keydown',{key:'Home'})
  expect(w.emitted('update:width')!.at(-1)).toEqual([180])
 })
 it('selects a module without triggering leaf navigation',async()=>{
  const w=mount(ZtMenu,{props:{items:modules,mode:'double',modelValue:'orders'}})
  await w.get('[data-category="team"]').trigger('click')
  expect(row(w,'members').exists()).toBe(true)
  expect(w.find('[data-menu-key="orders"]').exists()).toBe(false)
  expect(w.emitted('select')).toBeUndefined()
  await row(w,'members').trigger('click')
  expect(w.emitted('update:modelValue')).toEqual([['members']])
  await w.get('[data-category="blocked"]').trigger('click')
  expect(w.find('[data-menu-key="secret"]').exists()).toBe(false)
 })
 it('follows external leaf selection and preserves selection across collapse',async()=>{
  const w=mount(ZtMenu,{attachTo:document.body,global:{stubs:{teleport:true}},props:{items:modules,mode:'double',modelValue:'orders',collapsible:true}})
  await w.setProps({modelValue:'members'})
  expect(w.get('[data-category="team"]').attributes('aria-current')).toBe('true')
  await w.get('[aria-label="折叠菜单"]').trigger('click')
  expect(w.find('[data-menu-key="members"]').exists()).toBe(false)
  await w.get('[data-category="team"]').trigger('click')
  expect(row(w,'members').attributes('aria-current')).toBe('page')
  expect(row(w,'members').isVisible()).toBe(true)
  expect(w.classes()).toContain('is-collapsed')
  await row(w,'members').trigger('click')
  expect(w.find('.zt-menu__flyout').exists()).toBe(false)
  expect(w.classes()).toContain('is-collapsed')
  w.unmount()
 })
})

describe('collapsed double menu flyout',()=>{
 const modules:ZtMenuItem[]=[{key:'business',label:'业务',children:[{key:'nested',label:'报表',children:[{key:'daily',label:'日报'}]},{key:'disabled',label:'禁用',disabled:true}]},{key:'team',label:'团队',children:[{key:'members',label:'成员'}]}]
 it('keeps nested navigation in a themed teleport and closes only after leaf selection',async()=>{
  const w=mount(ZtConfigProvider,{attachTo:document.body,props:{theme:'dark',size:'large',borderRadius:4},slots:{default:()=>h(ZtMenu,{items:modules,mode:'double',collapsed:true})}})
  await w.get('[data-category="business"]').trigger('click')
  let panel=document.querySelector<HTMLElement>('.zt-menu__flyout')!
  expect(panel.style.colorScheme).toBe('dark')
  expect(panel.style.getPropertyValue('--zt-radius')).toBe('4px')
  expect(panel.classList.contains('zt-menu--large')).toBe(true)
  ;(panel.querySelector('[data-menu-key="nested"]') as HTMLElement).click()
  await new Promise(resolve=>setTimeout(resolve,0))
  expect(w.get('.zt-menu').classes()).toContain('is-collapsed')
  ;(panel.querySelector('[data-menu-key="disabled"]') as HTMLElement).click()
  await new Promise(resolve=>setTimeout(resolve,0))
  expect(document.querySelector('.zt-menu__flyout')).not.toBeNull()
  ;(panel.querySelector('[data-menu-key="daily"]') as HTMLElement).click()
  await new Promise(resolve=>setTimeout(resolve,0))
  expect(document.querySelector('.zt-menu__flyout')).toBeNull()
  expect(w.findComponent(ZtMenu).emitted('update:collapsed')).toBeUndefined()
  expect(w.findComponent(ZtMenu).emitted('update:modelValue')).toEqual([['daily']])
  w.unmount()
 })
 it('switches modules, dismisses outside and restores trigger focus on Escape',async()=>{
  const w=mount(ZtMenu,{attachTo:document.body,props:{items:modules,mode:'double',collapsed:true}})
  await w.get('[data-category="business"]').trigger('click')
  await w.get('[data-category="team"]').trigger('click')
  expect(document.querySelector('.zt-menu__flyout')!.textContent).toContain('成员')
  document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))
  await new Promise(resolve=>setTimeout(resolve,0))
  expect(document.querySelector('.zt-menu__flyout')).toBeNull()
  expect(document.activeElement).toBe(w.get('[data-category="team"]').element)
  await w.get('[data-category="team"]').trigger('click')
  document.body.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}))
  await new Promise(resolve=>setTimeout(resolve,0))
  expect(document.querySelector('.zt-menu__flyout')).toBeNull()
  w.unmount()
 })
})

describe('menu size geometry',()=>{
 it.each([['mini',252,64,60],['small',280,68,60],['default',312,68,60],['medium',340,72,60],['large',368,76,64]] as const)('uses %s default widths',async(size,width,rail,collapsed)=>{
  const w=mount(ZtMenu,{props:{mode:'double',size}})
  expect(w.attributes('style')).toContain(`width: ${width}px`)
  expect(w.attributes('style')).toContain(`--menu-rail-width: ${rail}px`)
  await w.setProps({collapsed:true})
  expect(w.attributes('style')).toContain(`width: ${collapsed}px`)
 })
 it('offsets custom widths from the default size baseline',async()=>{
  const w=mount(ZtConfigProvider,{props:{size:'mini'},slots:{default:()=>h(ZtMenu,{mode:'double'})}})
  await w.setProps({size:'large'})
  expect(w.get('.zt-menu').attributes('style')).toContain('width: 368px')
  w.unmount()
  const custom=mount(ZtMenu,{props:{mode:'double',width:420,railWidth:90,collapsedWidth:70}})
  await custom.setProps({size:'mini'})
  expect(custom.attributes('style')).toContain('width: 360px')
  expect(custom.attributes('style')).toContain('--menu-rail-width: 86px')
  await custom.setProps({collapsed:true})
  expect(custom.attributes('style')).toContain('width: 62px')
 })
})

 it('converts resized display width back to the default-size baseline',async()=>{
  const w=mount(ZtMenu,{props:{width:300,size:'large',resizable:true}})
  expect(w.attributes('style')).toContain('width: 356px')
  vi.spyOn(w.element,'getBoundingClientRect').mockReturnValue({width:356} as DOMRect)
  await w.get('[role=separator]').trigger('keydown',{key:'ArrowRight'})
  expect(w.emitted('update:width')!.at(-1)).toEqual([310])
  expect(w.attributes('style')).toContain('width: 366px')
  await w.setProps({size:'default'})
  expect(w.attributes('style')).toContain('width: 310px')
  w.unmount()
 })
