export const components = [
  { path: '/config-provider', name: 'ConfigProvider', title: '全局配置', group: '全局配置', description: '统一尺寸、明暗主题与圆角基准，支持嵌套覆盖。' },
  { path: '/icon', name: 'Icon', title: '图标', group: '基础与反馈', description: '内置图标、自定义图标与统一的尺寸颜色语义。' },
  { path: '/link', name: 'Link', title: '链接', group: '基础与反馈', description: '原生或路由导航、图标、状态与禁用行为。' },
  { path: '/text', name: 'Text', title: '文本', group: '基础与反馈', description: '语义标签、字号、状态和单行/多行省略。' },
  { path: '/scrollbar', name: 'Scrollbar', title: '滚动条', group: '基础与反馈', description: '统一轨道样式，同时保留原生滚动与触摸行为。' },
  { path: '/button', name: 'Button', title: '按钮', group: '基础与反馈', description: '触发操作、提交和加载反馈。' },
  { path: '/tag', name: 'Tag', title: '标签', group: '基础与反馈', description: '分类、标记与可移除标签。' },
  { path: '/badge', name: 'Badge', title: '徽标', group: '基础与反馈', description: '数量提醒与状态标记。' },
  { path: '/progress', name: 'Progress', title: '进度条', group: '基础与反馈', description: '完成率、任务状态和不确定进度。' },
  { path: '/radio', name: 'Radio', title: '单选框', group: '表单与选择', description: '从互斥选项中选择一项。' },
  { path: '/checkbox', name: 'Checkbox', title: '多选框', group: '表单与选择', description: '多项选择、组合与半选状态。' },
  { path: '/switch', name: 'Switch', title: '开关', group: '表单与选择', description: '启用或关闭一个设置。' },
  { path: '/slider', name: 'Slider', title: '滑块', group: '表单与选择', description: '步长调节、范围选择和键盘操作。' },
  { path: '/input', name: 'Input', title: '输入框', group: '表单与选择', description: '文本录入、清空及组合插槽。' },
  { path: '/upload', name: 'Upload', title: '上传', group: '表单与选择', description: '选择与拖拽、进度、取消重试及图片预览。' },
  { path: '/input-otp', name: 'InputOtp', title: '一次性密码', group: '表单与选择', description: '验证码分格输入、粘贴、自动填充与表单校验。' },
  { path: '/password', name: 'Password', title: '密码框', group: '表单与选择', description: '安全输入与密码显隐。' },
  { path: '/input-number', name: 'InputNumber', title: '数字输入框', group: '表单与选择', description: '数值范围、精度与步进。' },
  { path: '/select', name: 'Select', title: '选择器', group: '表单与选择', description: '单选、多选、本地筛选与远程搜索。' },
  { path: '/date-picker', name: 'DatePicker', title: '日期选择器', group: '日期与时间', description: '日期、双面板范围与节假日标识。' },
  { path: '/date-time-picker', name: 'DateTimePicker', title: '日期时间选择器', group: '日期与时间', description: '精确到秒的日期时间与范围。' },
  { path: '/form', name: 'Form', title: '表单', group: '表单与选择', description: '字段布局、分组、校验与提交。' },
  { path: '/menu', name: 'Menu', title: '菜单', group: '导航', description: '分组、多级子菜单、链接与键盘导航。' },
  { path: '/steps', name: 'Steps', title: '步骤条', group: '数据与流程', description: '呈现流程进度与步骤状态。' },
  { path: '/pagination', name: 'Pagination', title: '分页', group: '数据与流程', description: '控制页码、每页数量与跳页。' },
  { path: '/vtable-grid', name: 'VTableGrid', title: '数据表格', group: '数据与流程', description: '分页查询、排序、编辑与汇总。' },
  { path: '/modal', name: 'Modal', title: '弹窗', group: '弹层与交互', description: '集中处理确认和编辑任务。' },
  { path: '/drawer', name: 'Drawer', title: '抽屉', group: '弹层与交互', description: '在保留上下文时展示详情或编辑。' },
  { path: '/popover', name: 'Popover', title: '弹出框', group: '弹层与交互', description: '锚点浮层、多种触发方式与自动碰撞定位。' },
  { path: '/popconfirm', name: 'Popconfirm', title: '气泡确认框', group: '弹层与交互', description: '就地确认危险操作，支持异步确认。' },
  { path: '/tabs', name: 'Tabs', title: '标签页', group: '导航', description: '切换同层级内容，支持守卫、增删和键盘操作。' },
  { path: '/breadcrumb', name: 'Breadcrumb', title: '面包屑', group: '导航', description: '呈现页面层级与当前位置。' },
  { path: '/segmented', name: 'Segmented', title: '分段控制器', group: '表单与选择', description: '在少量互斥选项之间即时切换。' },
  { path: '/descriptions', name: 'Descriptions', title: '描述列表', group: '数据与流程', description: '响应式展示结构化标签和值。' },
  { path: '/collapse', name: 'Collapse', title: '折叠面板', group: '数据与流程', description: '展开和收起分组内容。' },
  { path: '/result', name: 'Result', title: '结果', group: '基础与反馈', description: '反馈完整任务的处理结果和后续动作。' },
  { path: '/image', name: 'Image', title: '图片', group: '基础与反馈', description: '加载后备、适应方式和全屏预览。' },
  { path: '/avatar', name: 'Avatar', title: '头像', group: '基础与反馈', description: '图片、图标或文字后备头像。' },
]
export const groups = [...new Set(components.map(item => item.group))]
export const scenarios = [
  { id: 'form-entry', title: '表单录入', description: '从字段校验到提交反馈，构建一份可用的业务表单。', components: ['form', 'input', 'select', 'input-number', 'button'], points: ['用 Form 管理数据和校验，FormItem 的 prop 对应字段名。', '提交前调用 validate，校验通过后再处理业务数据。', '通过 Form 的 size 和 disabled 统一控制子字段。'] },
  { id: 'query-filter', title: '查询筛选', description: '组合关键词、状态与日期范围，明确查询和重置行为。', components: ['input', 'select', 'date-picker', 'button'], points: ['区分正在编辑的筛选条件与已提交条件。', '空字符串、null 和空数组按各字段的值类型处理。', '查询条件变化后重置分页，避免落在不存在的页码上。'] },
  { id: 'data-list', title: '数据列表', description: '让搜索、列表与分页协同工作，处理无结果状态。', components: ['vtable-grid', 'pagination', 'tag', 'input'], points: ['本地数据先筛选再分页；远程数据由服务端返回当前页与总数。', '切换每页数量时将页码重置为第一页。', '大量数据、排序、编辑和汇总请使用 VTableGrid。'] },
  { id: 'overlay-edit', title: '弹层编辑', description: '在抽屉中编辑草稿，保存或取消后回到原有上下文。', components: ['drawer', 'modal', 'form', 'input', 'button'], points: ['打开时复制草稿，避免输入直接改写已保存数据。', '保存通过后关闭，取消则丢弃草稿。', '需要阻止意外关闭时使用 beforeClose，并保留键盘退出路径。'] },
  { id: 'status-flow', title: '状态与流程', description: '用步骤、标签和提示反馈正在进行的业务操作。', components: ['steps', 'tag', 'badge', 'button'], points: ['Steps 的 active 从 0 开始，表示当前步骤。', '用文字补充颜色含义，确保状态不只靠颜色表达。', '处理进行中时禁用重复操作，完成后提供明确结果。'] },
]
export const guides = [{ path: '/', title: '文档概览' }, { path: '/getting-started', title: '快速开始' }, { path: '/conventions', title: '通用约定' }, { path: '/scenarios', title: '场景指南' }, { path: '/components', title: '组件索引' }, { path: '/api', title: 'API 手册' }]
